### ISSUE TITLE
 [hauschmx] MkDocs exercise

### ISSUE THREAD

**Issue by cheriimoya** [Simulation-Software-Engineering/documentation-tools-exercise#15]
You can find my [repo here](https://github.com/cheriimoya/sse-mkdocs-exercise). The website is linked in the repo;)

**Comment by ajaust** [comment]
Looks good. I just have some minor remarks/questions:

- You set the `site_url` property, but it does not fit to your URL. 
- What does `shell.nix` do?

**Comment by cheriimoya** [comment]
the `shell.nix` file is the file i use to spawn a [nix shell](https://nixos.wiki/wiki/Development_environment_with_nix-shell). this gives me reproducible environments without putting stuff in my actual working environment (similar to a python virtual env)

you need the nix package manager for using this, tho

**Comment by cheriimoya** [comment]
btw, thats also why it says `` on the bottom of the html site

**Comment by ajaust** [comment]
Thanks for the follow-up. Maybe I will play around with the nix package manager some time. It sounds very interesting.
